home:
  monitors:
    - monitor: LVDS1
      workspaces:
        - name: '1:Web'
        - name: '2:Code'
        - name: '3:Tools'
        - name: '4:IM'
        - name: '5:Utils'
work:
  monitors:
    - monitor: eDP1
      workspaces:
        - name: '1:Web'
        - name: '3:Tools'
    - monitor: HDMI1
      workspaces:
        - name: '2:Code'
        - name: '4:IM'
        - name: '5:Utils'
single:
  monitors:
    - monitor: eDP1
      workspaces:
        - name: '1:Web'
        - name: '3:Tools'
        - name: '2:Code'
        - name: '4:IM'
        - name: '5:Utils'
