home:
  monitors:
    - monitor: LVDS1
      workspaces:
        - name: '1:Web'
        - name: '2:Code'
        - name: '3:Tools'
        - name: '4:IM'
        - name: '5:Utils'
work:
  monitors:
    - monitor: VGA-1
      workspaces:
        - name: '1:Web'
        - name: '3:Tools'
    - monitor: DVI-I-1
      workspaces:
        - name: '2:Code'
        - name: '4:IM'
        - name: '5:Utils'
